import random

ISO3166_1: set[str] = {
    "ad",
    "ae",
    "af",
    "ag",
    "ai",
    "al",
    "am",
    "ao",
    "aq",
    "ar",
    "as",
    "at",
    "au",
    "aw",
    "ax",
    "az",
    "ba",
    "bb",
    "bd",
    "be",
    "bf",
    "bg",
    "bh",
    "bi",
    "bj",
    "bl",
    "bm",
    "bn",
    "bo",
    "bq",
    "br",
    "bs",
    "bt",
    "bv",
    "bw",
    "by",
    "bz",
    "ca",
    "cc",
    "cd",
    "cf",
    "cg",
    "ch",
    "ci",
    "ck",
    "cl",
    "cm",
    "cn",
    "co",
    "cr",
    "cu",
    "cv",
    "cw",
    "cx",
    "cy",
    "cz",
    "de",
    "dj",
    "dk",
    "dm",
    "do",
    "dz",
    "ec",
    "ee",
    "eg",
    "eh",
    "er",
    "es",
    "et",
    "fi",
    "fj",
    "fk",
    "fm",
    "fo",
    "fr",
    "ga",
    "gb",
    "gd",
    "ge",
    "gf",
    "gg",
    "gh",
    "gi",
    "gl",
    "gm",
    "gn",
    "gp",
    "gq",
    "gr",
    "gs",
    "gt",
    "gu",
    "gw",
    "gy",
    "hk",
    "hm",
    "hn",
    "hr",
    "ht",
    "hu",
    "id",
    "ie",
    "il",
    "im",
    "in",
    "io",
    "iq",
    "ir",
    "is",
    "it",
    "je",
    "jm",
    "jo",
    "jp",
    "ke",
    "kg",
    "kh",
    "ki",
    "km",
    "kn",
    "kp",
    "kr",
    "kw",
    "ky",
    "kz",
    "la",
    "lb",
    "lc",
    "li",
    "lk",
    "lr",
    "ls",
    "lt",
    "lu",
    "lv",
    "ly",
    "ma",
    "mc",
    "md",
    "me",
    "mf",
    "mg",
    "mh",
    "mk",
    "ml",
    "mm",
    "mn",
    "mo",
    "mp",
    "mq",
    "mr",
    "ms",
    "mt",
    "mu",
    "mv",
    "mw",
    "mx",
    "my",
    "mz",
    "na",
    "nc",
    "ne",
    "nf",
    "ng",
    "ni",
    "nl",
    "no",
    "np",
    "nr",
    "nu",
    "nz",
    "om",
    "pa",
    "pe",
    "pf",
    "pg",
    "ph",
    "pk",
    "pl",
    "pm",
    "pn",
    "pr",
    "ps",
    "pt",
    "pw",
    "py",
    "qa",
    "re",
    "ro",
    "rs",
    "ru",
    "rw",
    "sa",
    "sb",
    "sc",
    "sd",
    "se",
    "sg",
    "sh",
    "si",
    "sj",
    "sk",
    "sl",
    "sm",
    "sn",
    "so",
    "sr",
    "ss",
    "st",
    "sv",
    "sx",
    "sy",
    "sz",
    "tc",
    "td",
    "tf",
    "tg",
    "th",
    "tj",
    "tk",
    "tl",
    "tm",
    "tn",
    "to",
    "tr",
    "tt",
    "tv",
    "tw",
    "tz",
    "ua",
    "ug",
    "um",
    "us",
    "uy",
    "uz",
    "va",
    "vc",
    "ve",
    "vg",
    "vi",
    "vn",
    "vu",
    "wf",
    "ws",
    "ye",
    "yt",
    "za",
    "zm",
    "zw",
}
WINDOWS_PHONE_DEVICES = [
    "HTC_HD2_T8585",
]
WINDOWS_NT_VER = [
    "Windows NT",
    "Windows NT 4.0",
    "Windows NT 5.0",
    "Windows NT 5.1",
]
WINDOWS_VER = WINDOWS_NT_VER + [
    "Windows 3.1",
    "Windows 95",
    "Windows 98",
    "WINDOWS_CE",
]
MOZILLA = [
    "Mozilla/1.22",
    "Mozilla/2.0",
    "Mozilla/3.0",
    "Mozilla/4.0",
    "Mozilla/4.08",
    "Mozilla/4.78",
    "Mozilla/5.0",
    "Mozilla/5.001",
    "Mozilla/6.0",
]
OPERA = [
    "Opera",
    "Opera/12.0",
    "Opera/5.02",
    "Opera/5.12",
    "Opera/6.0",
    "Opera/6.01",
    "Opera/6.02",
    "Opera/6.03",
    "Opera/6.04",
    "Opera/6.05",
    "Opera/6.11",
    "Opera/6.12",
    "Opera/7.0",
    "Opera/7.01",
    "Opera/7.03",
    "Opera/7.11",
    "Opera/7.21",
    "Opera/7.23",
    "Opera/7.50",
    "Opera/7.51",
    "Opera/7.53",
    "Opera/7.54",
    "Opera/8.0",
    "Opera/8.01",
    "Opera/8.02",
    "Opera/8.50",
    "Opera/8.51",
    "Opera/8.52",
    "Opera/8.53",
    "Opera/8.54",
    "Opera/9.00",
    "Opera/9.01",
    "Opera/9.02",
    "Opera/9.10",
    "Opera/9.12",
    "Opera/9.20",
    "Opera/9.21",
    "Opera/9.22",
    "Opera/9.23",
    "Opera/9.24",
    "Opera/9.25",
    "Opera/9.26",
    "Opera/9.27",
    "Opera/9.5",
    "Opera/9.50",
    "Opera/9.51",
    "Opera/9.52",
    "Opera/9.60",
    "Opera/9.61",
    "Opera/9.62",
    "Opera/9.63",
    "Opera/9.64",
    "Opera/9.70",
    "Opera/9.80",
]
MSIE_VER = [
    "2.0",
    "3.0",
    "3.0B",
    "3.01",
    "4.0",
    "4.01",
    "4.5",
    "5.0",
    "6.0",
    "7.0",
    "8.0",
    "9.0",
    "10.0",
    "11.0",
]
DOTNET = [
    ".NET CLR 1.1.4322",
    ".NET CLR 2.0.50727",
]
CHROME_MAX_VER = 134
MSEDGE_CHROMIUM_MIN_VER = 80


def random_chrome(variant, is_dev: bool):
    p1 = random.randint(MSEDGE_CHROMIUM_MIN_VER, CHROME_MAX_VER)
    p2 = 0
    p3 = p1 * 20 + random.randint(0, 20)
    p4 = random.randint(0, 200)
    return f"{p1}.{p2}.{p3}.{p4}"


def give_me_a_ua():
    CPU_ARCH = [
        random.choice(["x32", "x86", "i386", "i486", "i586", "i686"]),
        random.choice(["x64", "amd64", "AMD64", "x86_64"]),
        random.choice(["arm64", "aarch64", "arm_64"]),
        "ia64",
        "alpha",
        "alpha-64",
        "armv7l",
        "arm",
        "PPC",
        "PPC64",
        "riscv",
        "riscv32",
        "riscv64",
        "riscv128",
        "loongarch32",
        "loongarch64",
        "mips",
        random.choice(["mips32", "MIPS32"]),
        "mips64",
        "sparc",
        "sparc64",
    ]
    WINDOWS_PHONE_VER = [
        "({WINDOWS_NT_VER}; U; {lang})",
    ]
    MSIE = [
        "(compatible; {MSIE_VER}; {WINDOWS_VER})",
    ]
    LINUX = [
        random.choice(
            [
                "2.4" + str(random.choice(range(0, 20))),
                "2.6" + str(random.choice(range(0, 40))),
            ]
        ),
        "3." + str(random.choice(range(0, 20))),
        "4." + str(random.choice(range(0, 21))),
        "5." + str(random.choice(range(0, 20))),
        "6." + str(random.choice(range(0, 15))),
    ]
    OPERA_FINAL = [
        "{MOZILLA} (compatible; {MSIE_VER}; Linux 2.4.0-4GB {CPU_ARCH})",
    ]
    final = [
        "{WINDOWS_PHONE_DEVICES} {OPERA} {WINDOWS_PHONE_VERSION}",
        "{MOZILLA} {MSIE}",
        "{MOZILLA} {2} {3} {OPERA}  [{ISO3166_1}]",
        "{MOZILLA} {2} {3} {4}",
        "{MOZILLA} {2} {3} {4}",
        "{MOZILLA} {2} {3} {4}",
        "{MOZILLA} {2} {3} {4}",
        "{MOZILLA} {2} {3} {4}",
        "{MOZILLA} {2} {3} {4}",
        "{MOZILLA} {2} {3} {4}",
    ]

    return random.choice(final)
