# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Live_dm_v2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Live_dm_v2.proto\"\xc7\x03\n\x05\x64m_V2\x12\x0c\n\x04\x64mid\x18\x01 \x01(\x03\x12\x13\n\x0b\x64mid_unique\x18\x02 \x01(\t\x12\x0c\n\x04mode\x18\x03 \x01(\r\x12\x10\n\x08\x66ontsize\x18\x04 \x01(\r\x12\r\n\x05\x63olor\x18\x05 \x01(\r\x12\x0f\n\x07midHash\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x12\r\n\x05\x63time\x18\x08 \x01(\x04\x12\x12\n\nunknown_09\x18\t \x03(\x0c\x12\x0e\n\x06\x64mid_2\x18\n \x01(\x03\x12\x12\n\nunknown_11\x18\x0b \x03(\x0c\x12\x12\n\nunknown_12\x18\x0c \x03(\x0c\x12 \n\x0b\x63hat_bubble\x18\r \x01(\x0b\x32\x0b.chatBubble\x12\x0f\n\x07\x64m_type\x18\x0e \x01(\r\x12\x15\n\x05\x65mots\x18\x0f \x03(\x0b\x32\x06.emots\x12\x12\n\nunknown_16\x18\x10 \x03(\x0c\x12\x12\n\nunknown_17\x18\x11 \x03(\x0c\x12\x19\n\x07lottery\x18\x12 \x01(\x0b\x32\x08.lottery\x12\x12\n\nunknown_19\x18\x13 \x03(\x0c\x12\x12\n\nunknown_20\x18\x14 \x03(\x0c\x12\x12\n\nunknown_21\x18\x15 \x03(\x0c\x12\x12\n\nunknown_22\x18\x16 \x03(\x0c\x12\x12\n\nunknown_23\x18\x17 \x03(\x0c\"4\n\x05\x65mots\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\t\x12\x1d\n\x06\x64\x65tail\x18\x02 \x01(\x0b\x32\r.emots_detail\"\xa2\x01\n\x0c\x65mots_detail\x12\x17\n\x0f\x65moticon_unique\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x16\n\x0ein_player_area\x18\x03 \x01(\x08\x12\x12\n\nis_dynamic\x18\x04 \x01(\x08\x12!\n\x19unknown_emots_detail_0005\x18\x05 \x03(\x0c\x12\x0e\n\x06height\x18\x06 \x01(\r\x12\r\n\x05width\x18\x07 \x01(\r\"l\n\x07lottery\x12\x1c\n\x14unknown_lottery_0001\x18\x01 \x03(\x0c\x12\x12\n\nis_lottery\x18\x02 \x01(\r\x12\x11\n\tlotteryId\x18\x03 \x01(\t\x12\x1c\n\x14unknown_lottery_0004\x18\x04 \x03(\x0c\"\x85\x01\n\nchatBubble\x12\x18\n\x10\x63hat_bubble_type\x18\x01 \x01(\r\x12\x19\n\x11\x63hat_bubble_color\x18\x02 \x01(\t\x12 \n\x18unknown_chat_bubble_0003\x18\x03 \x03(\x0c\x12 \n\x18unknown_chat_bubble_0004\x18\x04 \x03(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Live_dm_v2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DM_V2._serialized_start=21
  _DM_V2._serialized_end=476
  _EMOTS._serialized_start=478
  _EMOTS._serialized_end=530
  _EMOTS_DETAIL._serialized_start=533
  _EMOTS_DETAIL._serialized_end=695
  _LOTTERY._serialized_start=697
  _LOTTERY._serialized_end=805
  _CHATBUBBLE._serialized_start=808
  _CHATBUBBLE._serialized_end=941
# @@protoc_insertion_point(module_scope)
